version: '2'
services:

  rp-mongodb:
    container_name: rp-mongodb
    image: mongo:3.2
    networks:
      - backend

  rp-frontend:
    container_name: rp-frontend
    build: ./RP-Frontend
    ports:
      - "1410:1410"
    networks:
      - public
    environment:
      - ASPNETCORE_APIURL="http://rp-backend:1479"

  rp-backend:
    container_name: rp-backend
    build: ./RP-Backend
    ports:
      - "1479:1479"
    networks:
      - public
      - backend
    environment:
      - ASPNETCORE_MONGOURL=mongodb://172.21.0.2:27017

  rp-preload:
    container_name: rp-preload
    build: ./RP-Preload
    networks:
      - backend
    environment:
      - ASPNETCORE_MONGOURL=mongodb://172.21.0.2:27017

networks:
  public:
    driver: bridge
  backend:
    driver: bridge
